# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f8a708e51689fea3973157aa8fe3f23e36d47c516b075e53a8c68c6b8b48c14a97cd26970b5ef63457d05e332083b1ad3175a96dd227182c144e4bf12143c7d

test:
  secret_key_base: 6152b66cba5a669312f2546e58d1e357fa7edf1173921d46a3955fc169cd92656287ed65c6e8c08247861186272fb8f50dbe0b8b3380840b8c999446a299211a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
